# Generated by Django 5.0.3 on 2024-04-11 18:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
                ('organizations_raw', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('rating', models.FloatField(null=True)),
                ('times_listed', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('genres_raw', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('summary', models.CharField(max_length=4000, null=True)),
                ('reviews_raw', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), size=None)),
                ('plays', models.IntegerField()),
                ('playing', models.IntegerField()),
                ('backlogs', models.IntegerField()),
                ('wishlist', models.IntegerField()),
                ('image_url', models.CharField(max_length=2000, null=True)),
                ('genres', models.ManyToManyField(related_name='games', to='games_rec.genre')),
                ('orgnaizations', models.ManyToManyField(to='games_rec.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=4000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games_rec.game')),
            ],
        ),
    ]
