# Generated by Django 5.0.3 on 2024-04-04 11:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres_raw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(max_length=3000),
        ),
    ]
