# Generated by Django 5.0.3 on 2024-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rec', '0002_alter_game_genres_raw_alter_game_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(max_length=4000),
        ),
    ]
