# Generated by Django 5.0.3 on 2024-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_rec', '0003_alter_game_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
